### ISSUE TITLE
Inconsistentence between code and simulation.

### ISSUE THREAD

**Issue by yujias424** [ZhaozhiQIAN/Single-Cause-Perturbation-NeurIPS-2021#2]
Dear Zhiqian,

Thank you so much for presenting this nice paper. 

However, I noticed that there may exist some name inconsistence between the code and simulation. For example, for Figure 3, you mentioned that 8 methods were included in the benchmark, including NN, NN-IPW, OP, DEC, VSR, SCP, CFR and DR-CFR. However, I could not find related name in the code (run_one_simulation.sh). In this file, there were eight methods, dor, scp, propensity, tarnet, vsr, drcrn, bmc overlap. Would you mind sharing some hints that which refers to which here?

Thank you!

**Comment by ZhaozhiQIAN** [comment]
Hi, the mentioned 'inconsistency' is resolved in the python notebooks for plotting and tabulating results, reproduced below:

```
    rename_dict = {
        'dor': 'NN', 'tarnet': 'CFR', 'propensity': 'NN-IPW', 'vsr': 'VSR', 'scp': 'SCP', 'drcrn': 'DR-CFR', 'bmc':'DEC', 'overlap': 'OP'
    }
```
